### ISSUE TITLE
discrepancies in most frequent indications

### ISSUE THREAD

**Issue by dbuijs** [hres/cvapps#108]
Under the ''Drugs'' tab, is the ''Most Frequent Indications'' graph reporting on the cases received for the drug only or for the cases that reported the AE with the drug?  In both cases, the numbers found in that graph when I searched for ''Zyprexa'' and ''abdominal pain'' for all dates, seems to be very low.

**Comment by aruu** [comment]
Plot title renamed to be clear that it is for all drugs listed in the reports.
By using CV Online, performing the same search, and counting the number of occurrences of indications (by first exporting the data), it can be seen that the data is accurate compared to CV Online.
