### ISSUE TITLE
include 0 case report as a possible result

### ISSUE THREAD

**Issue by dbuijs** [hres/cvapps#111]
When I select ''Zyprexa 20 mg'', I did not have the option of selecting ''abdominal pain'', is this because there are no reported cases with the two search terms?  I think we should still have the option of doing that search and obtaining 0 as a result.

**Comment by aruu** [comment]
this query is allowed in b1dc236997e12c0820a78c1f067afc5542c72b8e, doesn't return 0 (as there would be issues with graphs) but rather gives a warning pop-up and leaves graphs on previous successful result
