### ISSUE TITLE
List of drugs in drop-down should contain all products

### ISSUE THREAD

**Issue by aruu** [hres/cvapps#136]
I think it would be better that all drugs approved in Canada be available in the scroll down menu, whether there are reports or not for these products included in the CV database. I would prefer to get a nil message, rather than not finding the product.

**Comment by aruu** [comment]
need clarification; at most, we can include all results from the cv_drug_products table? what is the list of "all drugs approved in Canada" that is desired? the only concern would be is that this might slow down the UI.

**Comment by aruu** [comment]
related to #130

**Comment by dbuijs** [comment]
There are approximately 80K drug products. It is infeasible to populate this in a drop down and infeasible for humans to interact with a list this long. The search box has full search functionality.
