### ISSUE TITLE
Add feature to allow user to change chart types

### ISSUE THREAD

**Issue by aruu** [hres/cvapps#39]
Is it possible for the charts (e.g., reporter, serious, gender, etc.) to be provided in tabular form as an option? It makes it easier to copy and paste the data.  Also, some data is cut off in the chart boxes.

**Comment by kartik-goyal** [comment]
Have a look at this link, it uses plotly package and has a feature of editing graphs.
https://plot.ly/create/?fid=RPlotBot:3235
https://plot.ly/r/graphing-multiple-chart-types/

**Comment by dbuijs** [comment]
Please verify whether this is actually fully covered by #152 before closing this one
