### ISSUE TITLE
Gender (drop down filter)

### ISSUE THREAD

**Issue by aruu** [hres/cvapps#60]
Unpredictable results under ‘REACTIONS’; e.g. app criteria LIPITOR / NAUSEA / Female
N=354 (all reports meeting critieria)
Most frequent adverse events (PT): DRUG INEFFECTIVE, N=756
Most frequent adverse events (HLGT): ASTHENIC CONDITIONS, N=958
Graphs should show subset of filtered data

**Comment by dbuijs** [comment]
Closed Dec 8, 2016
