### ISSUE TITLE
Count of indications cannot be reproduced

### ISSUE THREAD

**Issue by aruu** [hres/cvapps#70]
Count of indications cannot be reproduced; some indications in app are not found in ARISg (e.g. Osteoporosis, GERD, RA, etc.).

ARISg:
Product Description LIPITOR
Product Flag Suspect; Concomitant
  
Count of Aer No
Blood cholesterol 5
Blood cholesterol increased 8
Blood pressure measurement 2
Dyslipidaemia 1
Hypercholesterolaemia 2
Hyperlipidaemia 2
Hypertension 2
Hypothyroidism 1
Product used for unknown indication 28
Grand Total 51

Drugs - ‘Most Frequent Indications’ bar graph
Criteria: LIPITOR / NAUSEA:
·         app,  n=597 reports
·         CV online (suspect), n=65
·         ARISg(suspect/concomitant), n=661

**Comment by dbuijs** [comment]
Closed Dec 8, 2016
