### ISSUE TITLE
Number of Reports in CV

### ISSUE THREAD

**Issue by aruu** [hres/cvapps#71]
Count of PTs by app seems to be smaller by a factor of 10x; most frequent PT in app (Drug ineffective) is not in top 10 counted in ARISg

Reactions - ‘Most Frequent Adverse Events’ bar graph
Criteria: LIPITOR / NAUSEA:
·         app,  n=597 reports
·         CV online (suspect), n=65
·         ARISg(suspect/concomitant), n=661

**Comment by dbuijs** [comment]
Closed Dec 8, 2016
