### ISSUE TITLE
App criteria: ATORVASTATIN  / NAUSEA

### ISSUE THREAD

**Issue by aruu** [hres/cvapps#74]
The ‘count’ for ATORVASTATIN-Nausea (142) does NOT match the results for CV online (186).

**Comment by aruu** [comment]
this is contingent on first deciding what's an appropriate term mapping for drug name/ingredients; if the active ingredient is just chosen directly from the table, it should match up

**Comment by dbuijs** [comment]
CVShiny is now connected to the same data source as CVP Online. Counts now match.
